networks:
  kr_net:

volumes:
  db_volume:

services:


  db:
    build:
      context: DB
    ports:
      - "54321:5432"
    container_name:
      db_postgres
    volumes:
      - db_volume:/home/
    networks:
      - kr_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  api_server:
    build:
      context: api_server
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    ports:
      - "5252:5252"
    environment:
      TZ: ${TZ}
    env_file:
      - .env
    container_name:
      api_server
    networks:
      - kr_net
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

